sispos/accounts/urls.py
from django.urls import path
from sispos.accounts.views import login, authorize, user, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login, name='login'),
    path('logout', logout_view, name='logout'),
    path('authorize', authorize, name='authorize'),
    path('user', user, name='user')
]

sispos/core/urls.py
from django.urls import path
from sispos.core.views import index


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

sispos/relatorios/urls.py
from django.urls import path
from sispos.relatorios import views

app_name = 'relatorios'

urlpatterns = [
    path('', views.relatorios_list, name='relatorios_list'),
    path('novo', views.relatorios_novo, name='relatorios_new'),
    path('update/<slug:slug>/', views.relatorios_update, name='relatorios_update')
]

sispos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('sispos.accounts.urls')),
    path('', include('sispos.core.urls')),
    path('relatorios/', include('sispos.relatorios.urls')),
    path('parecer/', include('sispos.parecer.urls')),
    path('/private/media/', include('private_files.urls')),
]

sispos/relatorios/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from sispos.accounts.models import User
from uuid import uuid4
from private_files import PrivateFileField


SEMESTER_1 = 'Primeiro semestre'
SEMESTER_2 = 'Segundo semestre'
SEMESTER_3 = 'Terceriro semestre'
SEMESTER_4 = 'Quarto semestre'
SEMESTER_5 = 'Quinto semestre'
SEMESTER_6 = 'Sexto semestre'
SEMESTER_7 = 'Sétimo semestre'


SEMESTER_CHOICES = (
    ('rds1', SEMESTER_1),
    ('rds2', SEMESTER_2),
    ('rds3', SEMESTER_3),
    ('rds4', SEMESTER_4),
    ('rds5', SEMESTER_5),
    ('rds6', SEMESTER_6),
    ('rds7', SEMESTER_7),
)

WAITING_RELATOR = 'Aguardando'
RELATOR_ASSIGNED = 'Encaminhado'
WAITING_PARECER_RELATOR = 'Aguardando'
PARECER_RELATOR_SUBMITED = 'Enviado'

STATUS_CHOICES = (
    ('waiting_relator', WAITING_RELATOR),
    ('relator_asigned', RELATOR_ASSIGNED),
    ('waiting_parecer_relator', WAITING_PARECER_RELATOR),
    ('parecer_relator_submited', PARECER_RELATOR_SUBMITED),
)


def limit_to_relator():
    return {'groups__name': 'relatores'}


class Relatorios(models.Model):
    nome = models.CharField('Nome', max_length=128)
    relator = models.ForeignKey(to=User, related_name='relator',
                                on_delete=models.SET_NULL, null=True,
                                limit_choices_to=limit_to_relator)
    orientador = models.CharField('Orientador', max_length=128)
    programa = models.CharField('Programa', max_length=20)
    relatorio = PrivateFileField('Relatório', upload_to='relatorios/%Y/%m/%d/')
    encaminhamento = PrivateFileField('Encaminhamento',
                                      upload_to='encaminhamentos/%Y/%m/%d/')
    user = models.ForeignKey(to=User, null=True, on_delete=models.SET_NULL)
    created = models.DateField('envio', auto_now_add=True)
    semestre = models.CharField('semestre', max_length=20,
                                choices=SEMESTER_CHOICES)
    uuid = models.UUIDField('uuid', default=uuid4, editable=False)
    state = models.CharField('state', max_length=128, 
                             default='waiting_relator', choices=STATUS_CHOICES)

    def get_absolute_url(self):
        return r('relatorios:relatorios_update', slug=str(self.uuid))

    def get_parecer_url(self):
        path_name = 'parecer:parecer_{}_new'.format(self.semestre)
        return r(path_name, slug=str(self.uuid))

sispos/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

sispos/core/templates/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SISPOS</title>
        <!-- Bootstrap core CSS -->
        {% bootstrap_css %}

        <!-- Layout css -->
        <link href="{% static 'css/layout.css' %}" rel="stylesheet">
        
    </head>

    <body>
        {% include 'menu.html' %}

        {% block content %}
        {% endblock content %}

        <!-- Bootstrap core JavaScript -->
        {% bootstrap_javascript jquery='full' %}

    </body>

</html>

sispos/core/templates/base_error.html
{% extends 'base.html' %}

{% block content %}

    <div class="header-top">
        <div class="container">
            <div class="card shadow">
                <div class="card-header">
                    {% block card_header %}
                    {% endblock card_header %}
                </div>
                <div class="card-body">
                    {% block card_body %}
                    {% endblock card_body %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

sispos/core/templates/base_front.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>SISPOS</title>
        <!-- Bootstrap core CSS -->
        {% bootstrap_css %}

        <!-- Layout css -->
        <link href="{% static 'css/layout.css' %}" rel="stylesheet">
        
    </head>

    <body class="front">
        {% include 'menu.html' %}

        {% block content %}
        {% endblock content %}

        <!-- Bootstrap core JavaScript -->
        {% bootstrap_javascript jquery='full' %}

    </body>

</html>

sispos/core/templates/index.html
{% extends 'base_front.html' %}

{% block content %}
<div class="masthead">
    <div class="container-fluid h-100">
        <div class="row h-100 align-items-center">
            <div class="col-6">
                <div class="card shadow mb-2">
                    <div class="card-body">
                        <h5 class="card-title">Submissão de relatórios de atividades</h5>
                        <p class="card-text">
                            Formulário para envio de relatórios de atividades de Mestrado e Doutorado
                        </p>      
                        <a href="{% url 'relatorios:relatorios_new' %}" class="btn btn-lg btn-outline-primary">Enviar Relatório</a>
                    </div>
                </div>
                {% if perms.relatorios.change_relatorios %}
                <div class="card shadow">
                    <div class="card-body">
                        <h5 class="card-title">Relatórios Enviados</h5>
                        <p class="card-text">
                            Administração dos relatórios de atividades enviados
                        </p>      
                        <a href="{% url 'relatorios:relatorios_list' %}" class="btn btn-lg btn-outline-primary">Listar Relatórios</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

sispos/core/templates/menu.html
<nav class="shadow navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <a href="{% url 'core:index' %}" class="navbar-brand">SISPOS</a>
    
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    </ul>
    {% if not user.is_authenticated %}
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">Login</a>
    {% endif %}
    {% if user.is_authenticated %}
        <div class="dropdown">
            <button 
                class="btn btn-outline-primary" 
                id="dropdown-login" 
                data-toggle="dropdown" 
                area-haspopup="true" 
                area-expanded="false"
            >
            {{ user.get_full_name }}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdown-login">
                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
            </div>
        </div>
    {% endif %}
</nav>

sispos/core/templates/sidebar.html
<div class="card">
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <a 
                href="{% url 'relatorios:relatorios_new' %}" 
                class="list-group-item list-group-item-action {% if request.path ==  "/relatorios/novo" %}active{% endif %}"
            >
                    Enviar Relatório
            </a>
            <a 
                href="{% url 'relatorios:relatorios_list' %}" 
                class="list-group-item list-group-item-action {% if request.path == '/relatorios/' %}active{% endif %}"
            >
                Lista de Relatórios
            </a>
        </ul>
    </div>
</div>